### ISSUE TITLE
intent.getExtras() returning null

### ISSUE THREAD

**Issue by dansherpa** [bryanl/FakeCamera#2]
The call to intent.getExtras() is returning null.  Any idea why that is happening?

**Comment by bryanl** [comment]
Are you running the code verbatim? Also, does it perform correctly once you first launch the app, but start returning null if you resume it?

**Comment by dansherpa** [comment]
Yes, verbatim. It returns null on initial open and on resume.

**Comment by bryanl** [comment]
I apologize, I haven't worked on this project in a while, so it took me a second to come up to speed. What I'm guessing you are seeing is something like the following in the log:

```
I/ActivityManager(   87): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.osesm.apps.fakecamera/.MainActivity } from pid 242
I/FakeCamera(  414): Unable to capture photo. Missing Intent Extras.
```

I'm also going to guess the way you arrived at this error is that you clicked on the FakeTestCamera icon in the app list? This application isn't made to be launched directly. I should probably update the app to explain how it should work.

The reason you would use this app is because you are developing another app, and what to use the Camera intent on the emulator (or on your real device) to take a picture. That process is a bit clunky, so this app just returns a stock image when it receives the intent. In short, this application is just a fake camera that returns an image to make testing smoother.

**Comment by bryanl** [comment]
I've created issue #3 to track this.

**Comment by dansherpa** [comment]
Aha! Soifi launch a barcode scanner app or something else that requests
camera intent then it should work?

**Comment by bryanl** [comment]
Yes, that's how it should be used.

**Comment by dansherpa** [comment]
Hmm... so when properly installed would you expect that I run an app that
request the camera intent that I would get the standard "Which app do you
want to use?" dialog.  I'm _not_ getting that - it just seems to be running
the default camera without asking.

**Comment by bryanl** [comment]
There are ways to reset default apps. I believe there are apps in the play store to do it.

**Comment by dansherpa** [comment]
I reset app preferences through "Settings -> Application Manager -> Reset
app preferences", however this doesn't seem to help, using a camera
(through RedLaser) just goes straight to the real camera, without prompting.

Is it possible newer versions of Android prevent camera requests from going
anywhere but the camera?  I am running JellyBean.

**Comment by dansherpa** [comment]
Looking at the Android camera API it seems like requests to take pictures
are done through the "android.hardware.Camera" class directly not through
intents.  I don't see how anyone could access an alternate camera, without
modifying Android?
